# Generated by Django 5.2.12 on 2026-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_leitor_emprestimo_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
